### ISSUE TITLE
Relationship support not plantuml multiline feature in description 

### ISSUE THREAD

**Issue by arc-sk** [tmorin/plantuml-libs#6]
Relationship("Business logic for\nmy special\nservice","HTTP")

Will produce a rendering
* first line bold - as expected
* second line normal font -> not expected
* third line normal font and ends with "<size></b>" -> not expected

**Comment by tmorin** [comment]
Hi,
For Relationship, it is not possible because the name of the relationship is in a `<b>` element.
And in creole (https://plantuml.com/creole) an element \n characters might not be valid.
I would recommend you to ask to the plantuml community if there is workaround (may be `skinparam wrapWidth` or `skinparam maxMessageSize`).
Best regards
